### ISSUE TITLE
Is it possible to add official pre-built files in repo or npm pkg?

### ISSUE THREAD

**Issue by PeterDaveHello** [maoberlehner/perfundo#65]
So that it'll be easier to include this lib on cdnjs.com :smile:

**Comment by maoberlehner** [comment]
ok - preferences about folder structure / naming - minified / unminified versions?

**Comment by PeterDaveHello** [comment]
Thanks for your prompt reply @maoberlehner.

I prefer to add a `dist` folder, both minified / unminified are fine, you can also add map file, it'll be good if you can name the files as readme says, like `perfundo.min.js`/`perfundo.min.css`, thanks.
